// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function ProcessFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessFiles'](arg1, arg2, arg3);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SelectAndReadTestFile() {
  return window['go']['main']['App']['SelectAndReadTestFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
