// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmDialog(arg1:string,arg2:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<main.BackendResponse>;

export function ListProfiles():Promise<Array<string>>;

export function LoadProfile(arg1:string):Promise<string>;

export function ProcessFiles(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SaveProfile(arg1:string):Promise<void>;

export function SelectAndReadTestFile():Promise<string>;

export function SelectDirectory():Promise<string>;
