# Nom de votre workflow, visible sur GitHub
name: Wails Build

# Déclenche le workflow à chaque push sur la branche 'main'
# ou manuellement depuis l'onglet "Actions" de GitHub
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Tâche pour compiler sur Windows
  build-windows:
    # Utilise la dernière version de Windows fournie par GitHub
    runs-on: windows-latest
    steps:
      # 1. Récupère le code de votre projet
      - uses: actions/checkout@v4

      # 2. Utilise l'action officielle de Wails qui s'occupe de TOUT
      - name: Build Wails App
        uses: dAppServer/wails-action@v2
        with:
          # Spécifie la plateforme cible
          platform: windows/amd64

      # 3. Met l'exécutable compilé à disposition pour le téléchargement
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: M.Tabule-windows
          path: build/bin/*.exe

  # Tâche pour compiler sur macOS (en bonus)
  build-macos:
    # Utilise la dernière version de macOS fournie par GitHub
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Wails App
        uses: dAppServer/wails-action@v2
        with:
          platform: darwin/universal
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: M.Tabule-macos
          path: build/bin/*.app
